### ISSUE TITLE
Failure on gradle 8: No signature of method: ...execute() is applicable for argument types

### ISSUE THREAD

**Issue by eekboom** [rackerlabs/gradle-jaxb-plugin#56]
After updating from gradle 7.6 to 8.0.1 we got the following exception.

To be honest we are using this fork, but issue tracking is not available there: https://github.com/seanrl/gradle-jaxb-plugin

```` 
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':product-models:xjc'.
	at ...
Caused by: groovy.lang.MissingMethodException: No signature of method: org.openrepose.gradle.plugins.jaxb.ant.AntXjc.execute() is applicable for argument types: (org.gradle.api.internal.project.DefaultAntBuilder, org.openrepose.gradle.plugins.jaxb.extension.XjcExtension_Decorated...) values: [org.gradle.api.internal.project.DefaultAntBuilder@28172255, ...]
	at ...
	at org.openrepose.gradle.plugins.jaxb.task.JaxbXjc.xjc(JaxbXjc.groovy:145)
	at org.openrepose.gradle.plugins.jaxb.task.JaxbXjc$xjc$0.callCurrent(Unknown Source)
	at org.openrepose.gradle.plugins.jaxb.task.JaxbXjc.start(JaxbXjc.groovy:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at ...
````

**Comment by seanrl** [comment]
The latest version of the https://github.com/seanrl/gradle-jaxb-plugin supports 8.0.2 (tested).  Should be fine on 8.0.1 as well.

I went ahead and enabled issue tracking on my fork as well - feel free to post any further issues there and hopefully I'll be notified by the system.

**Comment by eekboom** [comment]
Thanks a lot!
